CREATE TABLE OAUTH_CLIENT_DETAILS (
	CLIENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
	CLIENT_SECRET VARCHAR(255) NOT NULL,
	RESOURCE_IDS VARCHAR(255) DEFAULT NULL,
	SCOPE VARCHAR(255) DEFAULT NULL,
	AUTHORIZED_GRANT_TYPES VARCHAR(255) DEFAULT NULL,
	WEB_SERVER_REDIRECT_URI VARCHAR(255) DEFAULT NULL,
	AUTHORITIES VARCHAR(255) DEFAULT NULL,
	ACCESS_TOKEN_VALIDITY INT(11) DEFAULT NULL,
	REFRESH_TOKEN_VALIDITY INT(11) DEFAULT NULL,
	ADDITIONAL_INFORMATION VARCHAR(4096) DEFAULT NULL,
	AUTOAPPROVE VARCHAR(255) DEFAULT NULL
);
 
INSERT INTO OAUTH_CLIENT_DETAILS (
 	CLIENT_ID, CLIENT_SECRET, 
 	RESOURCE_IDS, SCOPE, 
 	AUTHORIZED_GRANT_TYPES, 
 	WEB_SERVER_REDIRECT_URI, AUTHORITIES,
	ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE)
VALUES(
	'USER_CLIENT_APP','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
	'USER_CLIENT_RESOURCE,USER_ADMIN_RESOURCE', 'role_admin,role_user',
	'authorization_code,password,refresh_token,implicit',
	NULL, NULL,
	900, 3600, '{}', NULL);
 

INSERT INTO USER (USERNAME, PASSWORD, EMAIL, ENABLED, ACCOUNT_EXPIRED, CREDENTIALS_EXPIRED, ACCOUNT_LOCKED) 
    VALUES 
    ('admin','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
    'william@gmail.com',1,0,0,0),
    ('user','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
    'john@gmail.com',1,0,0,0);
    
    
    