CREATE TABLE tracker.OAUTH_CLIENT_DETAILS (
	CLIENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
	CLIENT_SECRET VARCHAR(255) NOT NULL,
	RESOURCE_IDS VARCHAR(255) DEFAULT NULL,
	SCOPE VARCHAR(255) DEFAULT NULL,
	AUTHORIZED_GRANT_TYPES VARCHAR(255) DEFAULT NULL,
	WEB_SERVER_REDIRECT_URI VARCHAR(255) DEFAULT NULL,
	AUTHORITIES VARCHAR(255) DEFAULT NULL,
	ACCESS_TOKEN_VALIDITY INTEGER DEFAULT NULL,
	REFRESH_TOKEN_VALIDITY INTEGER DEFAULT NULL,
	ADDITIONAL_INFORMATION VARCHAR(4096) DEFAULT NULL,
	AUTOAPPROVE VARCHAR(255) DEFAULT NULL
);
 
INSERT INTO tracker.OAUTH_CLIENT_DETAILS (
 	CLIENT_ID, CLIENT_SECRET, 
 	RESOURCE_IDS, SCOPE, 
 	AUTHORIZED_GRANT_TYPES, 
 	WEB_SERVER_REDIRECT_URI, AUTHORITIES,
	ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE)
VALUES(
	'USER_CLIENT_APP','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
	'USER_CLIENT_RESOURCE,USER_ADMIN_RESOURCE', 'role_admin,role_user',
	'authorization_code,password,refresh_token,implicit',
	NULL, NULL,
	900, 3600, '{}', NULL);
 

INSERT INTO tracker.utente (CODICE_PERSONA, TIPO,NOME, COGNOME, USERNAME, PASSWORD, mail_aziendale, ACCOUNT_EXPIRED, CREDENTIALS_EXPIRED, ACCOUNT_LOCKED) 
    VALUES 
    ('dnsaoidasiodasioer3e43', 'I', 'admin', 'admin','admin','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
    'william@gmail.com',false, false, false),
    ('dnsaoidasiodasioe8097809','I','user', 'user','user','{bcrypt}$2a$10$EOs8VROb14e7ZnydvXECA.4LoIhPOoFHKvVF/iBZ/ker17Eocz4Vi',
    'john@gmail.com',false, false, false);
    